### ISSUE TITLE
Add GH_TOKEN & NPM_TOKEN in order to enable semantic-release

### ISSUE THREAD

**Issue by MichaelDeBoey** [MichaelDeBoey/gatsby-plugin-instagram-embed#3]
Like I said in #1:
> Checking out this branch & running `yarn install && semantic-release-cli setup` will setup Travis to have the correct `GH_TOKEN` & `NPM_TOKEN`

https://travis-ci.com/jlengstorf/gatsby-plugin-instagram-embed/jobs/266973079#L464

```bash
Error: GitHub authentication missing
    at validate (/home/travis/.npm/_npx/5567/lib/node_modules/travis-deploy-once/lib/validate.js:12:27)
    at module.exports (/home/travis/.npm/_npx/5567/lib/node_modules/travis-deploy-once/lib/travis-deploy-once.js:25:3)
    at module.exports (/home/travis/.npm/_npx/5567/lib/node_modules/travis-deploy-once/cli.js:47:14)
    at Object.<anonymous> (/home/travis/.npm/_npx/5567/lib/node_modules/travis-deploy-once/bin/travis-deploy-once.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at /home/travis/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
```

**Comment by jlengstorf** [comment]
Just ran it — it appears to have made additional changes, so I guess we'll see what happens 😂

**Comment by MichaelDeBoey** [comment]
I don't have this in [`gatsby-remark-embedder`](https://github.com/MichaelDeBoey/gatsby-remark-embedderr), so I think we can just revert these changes :-)
